### ISSUE TITLE
License info

### ISSUE THREAD

**Issue by diegocouto** [strateos/react-map-interaction#111]
Hi there 👋 

First of all, thank you very much for your hard work on `react-map-interaction`, I was amazed by how well-polished panning and zooming feel.

I've just noticed that there seems to be no information regarding the project's license. Is it correct to assume it's licensed under MIT or BSD?

Thanks a lot once again! 🙏

**Comment by scottyantipa** [comment]
True, I'll put a license. Thanks for the feedback.

**Comment by snowandmumu** [comment]
Hi there 👋

First of all, thank you very much for your hard work on react-map-interaction, It solved my big problem.

But, it is very necessary to have the license.

When will the project's license be ready？

Thanks a lot once again! 🙏

**Comment by githubuserPookie** [comment]
Where can I find the license for the code?

**Comment by scottyantipa** [comment]
Done https://github.com/strateos/react-map-interaction/blob/master/LICENSE
