### ISSUE TITLE
how to change transition based on slider value

### ISSUE THREAD

**Issue by swathithayalan** [strateos/react-map-interaction#61]
I want to control pan and zoom effects through the slider. is it possible?

**Comment by hatsuo** [comment]
You can use the component in controlled mode like described in the [Readme file](https://github.com/strateos/react-map-interaction#controlled).

You could then add change listeners to your sliders and change the state based on their current values.

**Comment by scottyantipa** [comment]
Thank you @hatsuo for the answer. Im closing this but please reopen if you still have an issue.
